version: '3.1'
services:
  api:
    image: node:10.16-slim
    container_name: 'api'
    ports:
      - '3333:3333'
    working_dir: '/usr/app'
    volumes:
      - ./:/usr/app
    command: 'npm run dev'
    # network_mode: "host"